### ISSUE TITLE
fingerprint unlock brightness not working correctly on havoc11

### ISSUE THREAD

**Issue by RisaShiramine** [ziasam/Meteoric#1]

**Comment by ziasam** [comment]
What happens when u press?

**Comment by RisaShiramine** [comment]
> What happens when u press?

Screen brightness goes highest in an instant when unlocking with FOD

**Comment by RisaShiramine** [comment]
> What happens when u press?

V3 has the same problem

**Comment by ziasam** [comment]
Solved in 7.2
