### ISSUE TITLE
Several issues on stock OOS 9R

### ISSUE THREAD

**Issue by gdw1986** [ziasam/Meteoric#2]
I have flashed latest version of stock OOS: 11.2.8.8.LE28DA. After flash meteoric kernel, the fingerprint is gone. And wifi doesn't work either.

**Comment by ziasam** [comment]
> I have flashed latest version of stock OOS: 11.2.8.8.LE28DA. After flash meteoric kernel, the fingerprint is gone. And wifi doesn't work either.

Meteoric is not for oos. It's for custom rom.
